# Generated by Django 3.1.2 on 2021-04-29 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Betting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0)),
                ('post_id', models.CharField(max_length=20)),
                ('betting_question', models.CharField(max_length=20, null=True)),
                ('betting_left', models.CharField(max_length=10, null=True)),
                ('betting_right', models.CharField(max_length=10, null=True)),
                ('participants_left', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('writer_id', models.CharField(max_length=20, null=True)),
                ('writer_name', models.CharField(max_length=20, null=True)),
                ('category', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_num', models.PositiveIntegerField(blank=True, default=0)),
                ('betting', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.betting')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('writer_id', models.CharField(max_length=20)),
                ('writer_name', models.CharField(max_length=20, null=True)),
                ('parent_comment_id', models.IntegerField(default=0)),
                ('mention', models.CharField(max_length=6, null=True)),
                ('depth', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_num', models.PositiveIntegerField(blank=True, default=0)),
                ('post', models.ForeignKey(limit_choices_to={'is_published': True}, on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.profile')),
            ],
        ),
    ]
