# Generated by Django 3.1.2 on 2021-04-19 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_num',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like_num',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('introduction', models.TextField(blank=True)),
                ('nickname', models.CharField(max_length=64)),
                ('username', models.CharField(default='', max_length=6)),
                ('point', models.PositiveIntegerField(blank=True, default=0)),
                ('category', models.PositiveIntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_comment_like', models.ManyToManyField(blank=True, related_name='user_comment_like', to='post.Comment')),
                ('user_commentlist', models.ManyToManyField(blank=True, related_name='user_commentlist', to='post.Comment')),
                ('user_post_like', models.ManyToManyField(blank=True, related_name='user_post_like', to='post.Post')),
                ('user_postlist', models.ManyToManyField(blank=True, related_name='user_postlist', to='post.Post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.profile'),
        ),
    ]
