# Generated by Django 3.1.2 on 2021-04-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='betting',
        ),
    ]
