# Generated by Django 3.1.2 on 2021-05-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
