# Generated by Django 3.1.2 on 2021-05-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_view_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='unlike_num',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='unlike_num',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
