# Generated by Django 3.1.2 on 2021-04-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210429_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='unknown', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.PositiveIntegerField(blank=True, default=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='unknown', max_length=6),
        ),
    ]
