# Generated by Django 3.1.2 on 2021-05-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210429_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_pk',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
