# Generated by Django 3.1.2 on 2021-05-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile_user_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
