# Generated by Django 3.1.2 on 2021-05-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_view_num'),
        ('login', '0005_remove_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_comment_like',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_comment_like', to='post.Comment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_commentlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_commentlist', to='post.Comment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_post_like',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_post_like', to='post.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_postlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_postlist', to='post.Post'),
        ),
    ]
