# Generated by Django 3.1.2 on 2021-05-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210524_1958'),
        ('login', '0006_auto_20210520_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_comment_unlike',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_comment_unlike', to='post.Comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_post_unlike',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_post_unlike', to='post.Post'),
        ),
    ]
