# Generated by Django 3.1.2 on 2021-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210525_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
