# Generated by Django 3.1.2 on 2021-05-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20210528_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
